server {
    listen 80;
    server_name stock.tripods.kr;

    # HTTP로 들어오면 HTTPS로 자동 리다이렉트
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name stock.tripods.kr;

    # 호스트 서버에서 도커 내부로 마운트될 Let's Encrypt 인증서 경로
    ssl_certificate /etc/letsencrypt/live/stock.tripods.kr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/stock.tripods.kr/privkey.pem;

    # 권장 SSL 보안 설정
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://app:8080;
        proxy_http_version 1.1;
        proxy_set_header Connection '';
        proxy_buffering off;
        proxy_cache off;
        chunked_transfer_encoding off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # SSE 스트리밍 연결 끊김 방지 (타임아웃 대폭 연장)
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }

    # 로그 설정
    access_log /var/log/nginx/prod_access.log;
    error_log /var/log/nginx/prod_error.log;
}
